apiVersion: apps/v1
kind: Deployment
metadata:
  name: jlopez-cryptominer-ccdemo
  labels:
    app: jlopez-cryptominer-ccdemo
spec:
  selector:
    matchLabels:
        app: jlopez-cryptominer-ccdemo
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jlopez-cryptominer-ccdemo
    spec:
      containers:
        - name: jlopez-cryptominer-ccdemo
          image: demo-image-name
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
